variables:
  VERSION: "1.0"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'

stages:
- build
- release

build:docs:
  stage: build
  when: manual
  image: registry.gitlab.com/gothicmultiplayerteam/buildimage:ubuntu-20.04-x64
  script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    - apt-get install -y doxygen graphviz
    - doxygen Doxyfile
  artifacts:
    name: "docs"
    paths:
      - docs/

pages:
  stage: build
  needs: [build:docs]
  script:
    - mv docs/html public
  after_script:
    - 'echo "Online documentation available under: ${CI_PAGES_URL}"'
  artifacts:
    paths:
      - public

docs:
  stage: build
  needs: [build:docs]
  script:
    - echo "Docs_job_id=${CI_JOB_ID}" >> job.env
  artifacts:
    name: "docs"
    paths:
      - docs/
    expire_in: never
    reports:
       dotenv: job.env

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  when: manual
  needs: [pages, docs]
  script:
    - echo "Created ${VERSION} release"
  release:
    tag_name: "${VERSION}"
    description: "./CHANGELOG.md"
    assets:
      links:
        - name: "docs"
          url: "${CI_PROJECT_URL}/-/jobs/${Docs_job_id}/artifacts/download"